run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-files:
    - versionware/example/releases/embed.go

linters-settings:
  gci:
    local-prefixes: github.com/snyk/vervet
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - ifElseChain
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
      - 'ginkgo\.It\("should'

linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - gci
    - gocritic
    - goconst
    - godot
    - gofmt
    - goimports
    - gocyclo
    # - gosec - Good to have linter but potential to introduce breaking changes.
    # - forbidigo - Good to have linter but potential to introduce breaking changes.
    - ifshort
    - lll
