run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-files:
    - versionware/example/releases/embed.go

linters-settings:
  gci:
    local-prefixes: github.com/snyk/vervet

linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - gci
    - gofmt
