nav:
- Go packages:
  - github.com/snyk/vervet/v6: github.com/snyk/vervet/v6.md
  - github.com/snyk/vervet/v6/config: github.com/snyk/vervet/v6/config.md
  - github.com/snyk/vervet/v6/versionware: github.com/snyk/vervet/v6/versionware.md
plugins:
- techdocs-core
site_name: vervet
