version: 2.1

orbs:
  go: circleci/go@1.9.0
  publish: snyk/publish@1
  prodsec: snyk/prodsec-orb@1.1

defaults: &defaults
  resource_class: small
  working_directory: ~/vervet
  docker:
    - image: cimg/go:1.21-node

test_vu_defaults: &test_vu_defaults
  resource_class: medium
  working_directory: ~/vervet/vervet-underground
  machine:
    image: ubuntu-2004:2023.10.1

vu_defaults: &vu_defaults
  resource_class: small
  working_directory: ~/vervet/vervet-underground
  docker:
    - image: cimg/go:1.21-node
  environment:
    DOCKER_BUILDKIT: 1

ignore_main_branch_filter: &ignore_main_branch_filter
  filters:
    branches:
      ignore:
        - main

only_main_branch_filter: &only_main_branch_filter
  filters:
    branches:
      only:
        - main

commands:
  gcr_auth:
    description: Auth GCR
    steps:
      - setup_remote_docker
      - run:
          name: GCR auth
          command: echo $GCLOUD_GCR_BUILDER | docker login -u _json_key --password-stdin https://gcr.io/snyk-main

  setup_build_remote_docker:
    steps:
      - setup_remote_docker:
          version: default      
          docker_layer_caching: false

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: Install spectral
          command: sudo npm install -g @stoplight/spectral@6.5.0
      - checkout
      - go/mod-download-cached
      - run:
          name: Verify testdata/output up to date
          command: go generate ./testdata
      - run:
          name: Run tests
          command: go test ./... -count=1

  test-vu:
    <<: *test_vu_defaults
    steps:
      - checkout:
          path: ~/vervet
      - go/install:
          version: 1.21.3
      - go/mod-download-cached
      - run:
          command: make test

  lint:
    docker:
      - image: golangci/golangci-lint:v1.51.0
    steps:
      - checkout
      - run:
          command: golangci-lint run -v ./...

  lint-vu:
    docker:
      - image: golangci/golangci-lint:v1.51.0
    steps:
      - checkout
      - run:
          command: cd vervet-underground && golangci-lint run -v ./...

  security-scans:
    <<: *vu_defaults
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          token-variable: SNYK_TOKEN
          org: platformeng_api

  build-vu:
    <<: *vu_defaults
    steps:
      - checkout:
          path: ~/vervet
      - gcr_auth
      - run:
          name: Build Docker Image
          command: make build-docker
      - publish/save-image:
          image_name: vervet-underground

  release:
    <<: *defaults
    steps:
      - checkout
      - run: |-
          go install github.com/caarlos0/svu@latest
          export VERSION=$(svu next)
          if [ -z $(git tag -l ${VERSION}) ]; then
            ./scripts/dist.bash
            ./scripts/release.bash
          fi

workflows:
  version: 2
  CI:
    jobs:
      - test:
          name: Test
          <<: *ignore_main_branch_filter

      - test-vu:
          name: Test VU
          <<: *ignore_main_branch_filter

      - lint:
          name: Lint
          <<: *ignore_main_branch_filter

      - lint-vu:
          name: Lint VU
          <<: *ignore_main_branch_filter

      - security-scans:
          name: Security Scans
          context:
            - platformeng_api
          <<: *ignore_main_branch_filter

      - build-vu:
          name: Build Docker Image
          context: snyk-docker-build
          requires:
            - Test VU
            - Lint VU

      - prodsec/container-scan:
          name: Scan VU Container
          docker_image_name: vervet-underground:${CIRCLE_WORKFLOW_ID}
          docker_image_filename: images/vervet-underground:${CIRCLE_WORKFLOW_ID}.tar.gz
          snyk_token_variable: SNYK_TOKEN
          snyk_organization: platformeng_api
          context:
            - platformeng_api
          requires:
            - Build Docker Image

  CD:
    jobs:
      - test:
          name: Test
          <<: *only_main_branch_filter

      - security-scans:
          name: Security Scans
          context:
            - platformeng_api
          <<: *only_main_branch_filter

      - build-vu:
          name: Build Docker Image
          context: snyk-docker-build
          <<: *only_main_branch_filter

      - release:
          name: Release
          context: nodejs-app-release
          requires:
            - Test

      - publish/publish:
          name: Publish Docker Image
          image_name: vervet-underground
          fedramp: "no"
          snyk_organization: platformeng_api
          snyk_token_variable: SNYK_TOKEN
          snyk_project_tags: component=pkg:github/snyk/vervet-underground@main,component=pkg:github/snyk/vervet@main
          context:
            - snyk-docker-build
            - infra-publish-orb
            - platformeng_api
            - snyk-bot-slack
          requires:
            - Build Docker Image
