version: 2.1

defaults: &defaults
  resource_class: small
  working_directory: ~/vervet
  docker:
    - image: circleci/golang:1.16-node

vu_metadata: &vu_metadata
    resource_class: small
    working_directory: ~/vervet/vervet-underground
    docker:
      - image: cimg/go:1.17-node

commands:
  gcr_auth:
    description: Auth GCR
    steps:
      - setup_remote_docker
      - run:
          name: GCR auth
          command: echo $GCLOUD_GCR_BUILDER | docker login -u _json_key --password-stdin https://gcr.io/snyk-main

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: Install spectral
          command: sudo npm install -g @stoplight/spectral@6.0.0-alpha3
      - checkout
      - attach_workspace:
          at: ~/vervet
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - run:
          name: Verify testdata/output up to date
          command: go generate ./testdata
      - run:
          name: Run tests
          command: go test ./... -count=1
      - run:
          command: make -C vervet-underground test

  lint:
    docker:
      - image: golangci/golangci-lint:v1.42.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet
      - run:
          command: golangci-lint run -v ./...

  lint-vu:
    docker:
      - image: golangci/golangci-lint:v1.42.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet/vervet-underground
      - run:
          command: golangci-lint run -v ./...

  build-vu:
    <<: *vu_metadata
    steps:
      - checkout:
          path: ~/vervet
      - run:
          name: build go vervet-undergound
          command: make build

  publish-vu:
    <<: *vu_metadata
    steps:
      - checkout:
          path: ~/vervet
      - gcr_auth
      - run:
          name: Build
          command: docker build -t gcr.io/snyk-main/vervet-underground:${CIRCLE_SHA1} .
      - run:
          name: Push
          command: docker push gcr.io/snyk-main/vervet-underground:${CIRCLE_SHA1}

  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet
      - run: |-
          go install github.com/smlx/ccv@latest
          export VERSION=$(ccv)
          if [ -z $(git tag -l $(ccv)) ]; then
            ./scripts/dist.bash
            ./scripts/release.bash
          fi

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: Test
      - lint:
          name: Lint
      - lint-vu:
          name: Lint VU

  release:
    jobs:
      - test:
          name: Test
          filters:
            branches:
              only: 'main'
      - build-vu:
          name: Build app
          context: snyk-docker-build
          filters:
            branches:
              only:
                - main
      - release:
          name: Release
          context: nodejs-app-release
          requires:
            - Test
          filters:
            branches:
              only:
                - main
      - publish-vu:
          name: Build and publish image
          context: snyk-docker-build
          requires:
            - Build app
          filters:
            branches:
              only:
                - main
