global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: vervet-underground
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - vervet-underground:8080
