package backstage

import (
	"bytes"
	"os"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/snyk/vervet/v4/testdata"
)

func TestRoundTripCatalog(t *testing.T) {
	catalogSrc := `
# Important user-authored comment
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: some-component # inline comment
---
apiVersion: backstage.io/v1alpha1
kind: API
# special instructions
metadata:
  name: some-api
`[1:]
	vervetAPI := `
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vervet-api
  annotations:
    snyk.io/vervet/generated-by: vervet
    snyk.io/vervet/version: 2021-06-04~experimental
    snyk.io/vervet/version/date: "2021-06-04"
    snyk.io/vervet/version/lifecycle: sunset
    snyk.io/vervet/version/stability: experimental
`[1:]
	c := qt.New(t)
	catalog, err := LoadCatalogInfo(bytes.NewBufferString(catalogSrc + vervetAPI))
	c.Assert(err, qt.IsNil)
	c.Assert(catalog.service, qt.Not(qt.IsNil))
	c.Assert(catalog.components, qt.HasLen, 1)
	var saveOutput bytes.Buffer
	c.Assert(catalog.Save(&saveOutput), qt.IsNil)
	c.Assert(saveOutput.String(), qt.Equals, catalogSrc)
}

func TestLoadCatalogEmpty(t *testing.T) {
	c := qt.New(t)
	catalog, err := LoadCatalogInfo(bytes.NewBufferString(``))
	c.Assert(err, qt.IsNil)
	c.Assert(catalog.service, qt.IsNil)
	c.Assert(catalog.components, qt.HasLen, 0)
}

func TestLoadCatalogNoService(t *testing.T) {
	c := qt.New(t)
	catalogSrc := `
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: some-place
  tags:
    - things
spec:
  type: url
`[1:]
	catalog, err := LoadCatalogInfo(bytes.NewBufferString(catalogSrc))
	c.Assert(err, qt.IsNil)
	c.Assert(catalog.service, qt.IsNil)
	c.Assert(catalog.components, qt.HasLen, 1)
	var saveOutput bytes.Buffer
	c.Assert(catalog.Save(&saveOutput), qt.IsNil)
	c.Assert(saveOutput.String(), qt.Equals, catalogSrc)
}

var catalogSrc = `
# Important user-authored comment
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: some-component # inline comment
spec:
  owner: "someone-else"
`[1:]

func TestLoadVersionsNoApis(t *testing.T) {
	c := qt.New(t)
	vervetAPIs, err := os.ReadFile(testdata.Path("catalog-vervet-apis.yaml"))
	c.Assert(err, qt.IsNil)
	catalog, err := LoadCatalogInfo(bytes.NewBufferString(catalogSrc))
	c.Assert(err, qt.IsNil)
	versionsRoot := testdata.Path("output")
	err = catalog.LoadVervetAPIs(testdata.Path("."), versionsRoot)
	c.Assert(err, qt.IsNil)

	var saveOutput bytes.Buffer
	err = catalog.Save(&saveOutput)
	c.Assert(err, qt.IsNil)
	c.Assert(saveOutput.String(), qt.Equals, catalogSrc+`
  providesApis:
    - Registry 2021-06-01~experimental
    - Registry 2021-06-04~experimental
    - Registry 2021-06-07~experimental
    - Registry 2021-06-13~beta
    - Registry 2021-06-13~experimental
    - Registry 2021-08-20~beta
    - Registry 2021-08-20~experimental
---
`[1:]+string(vervetAPIs))
}

func TestLoadVersionsSomeApis(t *testing.T) {
	c := qt.New(t)
	vervetAPIs, err := os.ReadFile(testdata.Path("catalog-vervet-apis.yaml"))
	c.Assert(err, qt.IsNil)
	catalog, err := LoadCatalogInfo(bytes.NewBufferString(catalogSrc + `
  providesApis:
    - someOtherApi
`[1:]))
	c.Assert(err, qt.IsNil)
	versionsRoot := testdata.Path("output")
	err = catalog.LoadVervetAPIs(testdata.Path("."), versionsRoot)
	c.Assert(err, qt.IsNil)

	var saveOutput bytes.Buffer
	err = catalog.Save(&saveOutput)
	c.Assert(err, qt.IsNil)
	c.Assert(saveOutput.String(), qt.Equals, catalogSrc+`
  providesApis:
    - someOtherApi
    - Registry 2021-06-01~experimental
    - Registry 2021-06-04~experimental
    - Registry 2021-06-07~experimental
    - Registry 2021-06-13~beta
    - Registry 2021-06-13~experimental
    - Registry 2021-08-20~beta
    - Registry 2021-08-20~experimental
---
`[1:]+string(vervetAPIs))
}
