run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true


linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  exhaustive:
    default-signifies-exhaustive: true
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
      - 'ginkgo\.It\("should'
  gci:
    local-prefixes: vervet-underground
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: vervet-underground
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  gomnd:
    checks:
      - argument
      - assign
      - case
      - condition
      - operation
      - return
  lll:
    line-length: 160
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  # ST1001: Dot imports that aren’t in external test packages are discouraged.
  stylecheck:
    checks: [ "all", "-ST1003" ]
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - goconst
#    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - ifshort
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - goconst
        - staticcheck
        - testpackage
