{
 "title": "Vervet Underground",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vu_scraper_run_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "vu_scraper_run_error_total" }
   ]
  },
  {
   "title": "Service Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service) (rate(vu_scraper_service_scrape_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Call Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, host) (rate(vu_scraper_service_scrape_http_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Collation Merge Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "vu_collator_merge_error_total", "legendFormat": "__auto" }
   ]
  }
 ]
}